In [10]:
import numpy as np
import pandas as pd

np.random.seed(100)
r = np.arange(80)
r =r.reshape((8, 10))
r = r.reshape((-1, 1))
r = r.reshape((-1, 8))

print(r.shape)

print(r)

print(r[1:3])
print(r[1:3, 0:3])

print(r[1: 3, 0: 1])
print(r[1:3, 0])

r = r.reshape(-1, 1)
print(r[0: 4])
print(r[0: 4, 0])
print(r[0, 0])


(10, 8)
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79]]
[[ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[ 8  9 10]
 [16 17 18]]
[[ 8]
 [16]]
[ 8 16]
[[0]
 [1]
 [2]
 [3]]
[0 1 2 3]
0


In [5]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/Users/chenchen/opt/anaconda3/envs/py37_vnpy/lib/python3.7/site-packages/tensorflow/_api/v2/version/__init__.py'>


## Tensors
A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, Tensorflow represents a tensors as n-dimensional arrays of base datatypes. Each tensor represents a partialy defined computation that will eventually produce a value.

In [9]:
# scalar value, rank 0
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.14, tf.float64)

rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>